#!/bin/sh

ln -s $HOME/dev/dotfiles/.zshrc $HOME/.zshrc
ln -s $HOME/dev/dotfiles/.aliases $HOME/
ln -s $HOME/dev/dotfiles/.profile $HOME/
ln -s $HOME/dev/dotfiles/sxhkd $HOME/.config/
ln -s $HOME/dev/dotfiles/ranger $HOME/.config/
ln -s $HOME/dev/dotfiles/nvim $HOME/.config/
ln -s $HOME/dev/dotfiles/bspwm $HOME/.config/
ln -s $HOME/dev/dotfiles/.xinitrc $HOME/
ln -s $HOME/dev/dotfiles/rofi $HOME/.config/
ln -s $HOME/dev/dotfiles/login $HOME/.config/
ln -s $HOME/dev/dotfiles/chrome $HOME/.mozilla/firefox/*.default/
ln -s $HOME/dev/dotfiles/Xresources $HOME/.config
