#!/bin/sh
## Load appearance settings
xsetroot -cursor_name left_ptr &
export GTK2_RC_FILES="$HOME/.gtkrc-2.0" &
xrdb merge .Xresources &
## Wallpaper script. Chooses a random wallpaper from ~/Pictures/wallpapers
wallpaper &
## compositing. Required for shadows, transparency and stuff. 
# Alter compton settings if using intel graphics
GRAPHIC_CARD=$(lspci | grep -i "vga" | sed 's/.*://' | sed 's/(.*//' | sed 's/^[ \t]*//')
if [[ $(echo $GRAPHIC_CARD | grep -i 'intel\|lenovo') != "" ]]; then MCODE='initrd=\intel-ucode.img'
  sed -i 's/"xrender"/"glx"/' ~/.config/compton.conf
  grep -q 'vsync = "opengl-swc";' ~/.config/compton.conf || echo 'vsync = "opengl-swc";' >> ~/.config/compton.conf
fi
## Reduces flicker. Disabling saves resources.
compton -b &
## enable local fonts in .fonts directory
xset +fp /usr/share/fonts/local &
xset +fp /usr/share/fonts/misc &
xset +fp ~/.fonts &
xset fp rehash &
#update font cache
#fc-cache -fv &
## Automount removable media
devmon &
## powersaving options
## Make monitor settings persist between reboots
eval $(awk -F'=' '/Exec=/ {print $2}' ~/.config/autostart/lxrandr-autostart.desktop) &
## Gnome keyring
gnome-keyring-daemon &
thunar --daemon &
clipmenud &
# nextcloud --background &
