#! /bin/sh
#  ____  ___  ____  _    _  __  __  ____   ___ 
# (  _ \/ __)(  _ \( \/\/ )(  \/  )(  _ \ / __)
#  ) _ <\__ \ )___/ )    (  )    (  )   /( (__ 
# (____/(___/(__)  (__/\__)(_/\/\_)(_)\_) \___)
#
# ASCII Art: http://www.patorjk.com/software/taag/#p=display&f=Bulbhead&t=BSPWMRC
#

# Constants
gap=5
PANEL_HEIGHT=0
export gap
export PANEL_HEIGHT

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

##Color settings
bspc config focused_border_color "#50FA7B"
bspc config normal_border_color "#222D32"
#"#000000"
bspc config presel_feedback_color "#BD93F9"
#"#8F3724"
bspc config border_width 1

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config split_ratio         0.53

###This automatically creates and names desktops for multiple monitors.
workspaces_multimonitor &

bspc rule -a viewnior state=floating center=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a spotify state=pseudo_tiled
bspc rule -a Emacs state=tiled
bspc rule -a Steam monitor=DVI-I-1 desktop=!occupied
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a Docky layer=above border=off manage=on
bspc rule -a firefox private=on monitor=HDMI-0
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a hl2_linux monitor=HDMI-0 state=fullscreen
bspc rule -a '*:*:YAD' state=floating
bspc rule -a '*:*:Drill' state=floating
bspc rule -a '*:*:Save Document?' state=floating

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating hidden=on
# check scratchpad already running
[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad -e ~/.local/bin/scratch &

bspc rule -a dropdown monitor=HDMI-0 sticky=on state=floating hidden=on
run_once termite --class dropdown -e "zsh -i" &

# Maps wacom taplet to main monitor
xinput map-to-output 19 HDMI1 

##Autostart apps
#Keybindings daemon
#sxhkd &
#Source autostartfile. Uncomment this if you use bspwm-git
#. $HOME/.config/bspwm/autostart
polybar default &
polybar secondary &
run_once desknamer.sh &

# Alter compton settings if using intel graphics
GRAPHIC_CARD=$(lspci | grep -i "vga" | sed 's/.*://' | sed 's/(.*//' | sed 's/^[ \t]*//')
if [[ $(echo $GRAPHIC_CARD | grep -i 'intel\|lenovo') != "" ]]; then MCODE='initrd=\intel-ucode.img'
  sed -i 's/"xrender"/"glx"/' ~/.config/compton.conf
  grep -q 'vsync = "opengl-swc";' ~/.config/compton.conf || echo 'vsync = "opengl-swc";' >> ~/.config/compton.conf
fi
